# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('deck_id', models.AutoField(primary_key=True, serialize=False)),
                ('deck_name', models.CharField(max_length=250)),
                ('side', models.CharField(choices=[('R', 'Runner'), ('C', 'Corporation')], max_length=1)),
                ('faction', models.CharField(choices=[('H', 'Haas-Bioroid'), ('J', 'Jinteki'), ('W', 'Weyland'), ('N', 'NBN'), ('A', 'Anarch'), ('S', 'Shaper'), ('C', 'Criminal'), ('P', 'Apex'), ('D', 'Adam'), ('L', 'Sunny Lebeau')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('W', 'Win'), ('L', 'Lose')], max_length=1)),
                ('round_num', models.IntegerField(null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league_tracker.Event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='records',
            name='opponent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league_tracker.User'),
        ),
        migrations.AddField(
            model_name='records',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league_tracker.User'),
        ),
        migrations.AddField(
            model_name='decks',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_tracker.User'),
        ),
    ]
