# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('deck_id', models.AutoField(primary_key=True, serialize=False)),
                ('deck_name', models.CharField(max_length=250)),
                ('side', models.CharField(choices=[('R', 'Runner'), ('C', 'Corporation')], max_length=1)),
                ('faction', models.CharField(choices=[('H', 'Haas-Bioroid'), ('J', 'Jinteki'), ('W', 'Weyland'), ('N', 'NBN'), ('A', 'Anarch'), ('S', 'Shaper'), ('C', 'Criminal'), ('P', 'Apex'), ('D', 'Adam'), ('L', 'Sunny Lebeau')], max_length=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_tracker.User')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('W', 'Win'), ('L', 'Lose')], max_length=1)),
                ('points_win', models.IntegerField()),
                ('points_lose', models.IntegerField()),
                ('flatline', models.BooleanField()),
                ('opponent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league_tracker.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league_tracker.User')),
            ],
        ),
    ]
