# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_tracker', '0002_decks_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('league_name', models.CharField(default='New League', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='decks',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='league_tracker.League'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='records',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='league_tracker.League'),
            preserve_default=False,
        ),
    ]
