# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_tracker', '0003_auto_20170822_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
