# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_tracker', '0004_auto_20170904_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bye',
            field=models.BooleanField(default=False),
        ),
    ]
