# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_tracker', '0004_auto_20170822_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='flatline',
        ),
        migrations.RemoveField(
            model_name='records',
            name='points_lose',
        ),
        migrations.RemoveField(
            model_name='records',
            name='points_win',
        ),
    ]
