# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_tracker', '0005_auto_20170829_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decks',
            name='league',
        ),
        migrations.RemoveField(
            model_name='records',
            name='league',
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
