# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_tracker', '0005_user_is_bye'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='linked_record',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
