# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_tracker', '0006_records_linked_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decks',
            name='deck_name',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='faction',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='side',
        ),
        migrations.AddField(
            model_name='decks',
            name='corp_faction',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='decks',
            name='corp_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='decks',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league_tracker.Event'),
        ),
        migrations.AddField(
            model_name='decks',
            name='runner_faction',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='decks',
            name='runner_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='decks',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league_tracker.User'),
        ),
    ]
