# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_tracker', '0007_auto_20170905_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league_tracker.Decks'),
        ),
    ]
