# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_tracker', '0008_records_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='deck',
        ),
        migrations.AlterUniqueTogether(
            name='decks',
            unique_together=set([('user_id', 'game')]),
        ),
    ]
