# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_tracker', '0011_auto_20170905_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='deck_id',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='game',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='records',
            name='deck',
        ),
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
